spring:
  cloud:
    nacos:
      discovery:
        server-addr: http://127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: hello123
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu
#        - id: consumer
#          uri: http://localhost:8081
#          predicates:
#            - Path=/user/hello
        - id: student
          uri: lb://nacos-client
          predicates:
            - Path=/studentApi/**
        - id: parent
          uri: lb://nacos-client
          predicates:
            - Path=/parentApi/**
        - id: teacher
          uri: lb://nacos-client
          predicates:
            - Path=/teacherApi/**
        - id: user
          uri: lb://nacos-client
          predicates:
            - Path=/userApi/login
        - id: organ
          uri: lb://nacos-client
          predicates:
            - Path=/organApi/**
        - id: Iot
          uri: lb://nacos-client
          predicates:
            - Path=/iotApi/**
#          filters:
#            - AddRequestHeader=X-Request-Foo, Bar
#            - name: RequestRateLimiter
#              args:
#                # 令牌桶每秒填充平均速率
#                redis-rate-limiter.replenishRate: 1
#                # 令牌桶的上限
#                redis-rate-limiter.burstCapacity: 2
#                # 使用SpEL表达式从Spring容器中获取Bean对象
#                key-resolver: "#{@pathKeyResolver}"

  application:
    name: gateway
server:
  port: 8889


